apiVersion: v1
kind: PersistentVolume
metadata:
  name: protogcn-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/eunji/Desktop/project/k8s-multi-container-system/proto-gcn
