# 학습 workflow 정의
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: protogcn-run-
spec:
  entrypoint: run
  imagePullSecrets:        # 전체 템플릿에 적용
    - name: dockerhub-secret
  arguments:
    parameters:
    - name: user

  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: protogcn-pvc

  templates:
  - name: run
    dag:
      tasks:
      - name: train
        template: train-one
        arguments:
          parameters:
            - name: pkl_path
              value: "/data/data/*/*.pkl"  # 하위 폴더의 pkl 파일들
            - name: output_dir
              value: "/data/results/{{workflow.parameters.user}}"

  - name: train-one
    inputs:
      parameters:
      - name: pkl_path
      - name: output_dir
    container:
      image: local-proto-gcn:v7
      command: ["python", "auto_protogcn.py"]
      imagePullPolicy: Never
      securityContext:
        privileged: true
      env:
      - name: DATASET_PKL
        value: "{{inputs.parameters.pkl_path}}"
      - name: RUNS_ROOT
        value: "{{inputs.parameters.output_dir}}"
      - name: CUDA_VISIBLE_DEVICES
        value: ""
      volumeMounts:
      - name: shared-volume
        mountPath: /data
      - name: dev
        mountPath: /dev
      - name: nvidia-libs
        mountPath: /usr/local/nvidia
        readOnly: true
    volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: nvidia-libs
      hostPath:
        path: /usr/lib/x86_64-linux-gnu

  # 3. CSV 병합
  - name: merge-results
    container:
      image: bianbbc87/csdc-protogcn-merge:latest
      command: ["python", "/app/index.py"]
      volumeMounts:
      - name: shared-volume
        mountPath: /data
